LINUXINCLUDE += -I$(srctree)/drivers/iommu
LINUXINCLUDE += -I$(srctree)/drivers/staging/android/ion
LINUXINCLUDE += -I$(srctree)/drivers/gpu/drm/hisi

obj-$(CONFIG_HISI_IODOMAIN_API) += hisi-iommu-map.o
obj-$(CONFIG_HISI_IOMMU_LPAE) += hisi_smmu_lpae.o
