obj-y += cpu_netlink.o
obj-$(CONFIG_HW_VIP_THREAD) += proc_fork_nl.o
obj-$(CONFIG_HW_IAWARE_THREAD_BOOST) += proc_comm_nl.o

obj-$(CONFIG_TASK_DELAY_ACCT) += delayacct.o
obj-$(CONFIG_DETECT_HUAWEI_HUNG_TASK) += huawei_hung_task.o
obj-$(CONFIG_DETECT_HUAWEI_MMAP_SEM) += huawei_check_mmap_sem.o
